name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd instarocket && cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='senhamudar' -PMYAPP_UPLOAD_KEY_PASSWORD='senhamudar'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: instarocket/android/app/build/outputs/apk/release/

